((nil . ((indent-tabs-mode . t)
         (tab-width . 4)
         (fill-column . 80)))
 (c-mode . ((c-file-style . "k&r")))
 (nxml-mode . ((nxml-child-indent . 4)
			   (nxml-outline-child-indent . 4))))
